repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: env PYTHONPATH="." python3 -m pylint minigrad/
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        always_run: true
        pass_filenames: false
      - id: test
        name: test
        entry: env PYTHONPATH="." python -m pytest
        language: system
        always_run: true
        pass_filenames: false