repos:
  - repo: local
    hooks:
      - id: test ops
        name: test ops
        entry: env PYTHONPATH="." python -m pytest
        language: system
        always_run: true
        pass_filenames: false
      - id: lint
        name: lint
        entry: env PYTHONPATH="." python -m pylint --disable=all -e W0311 --jobs=0  **/*.py
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        always_run: true
        pass_filenames: false